"""empty message

Revision ID: 557b36013e40
Revises: 90efb5979fe1
Create Date: 2022-06-01 21:40:16.820364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557b36013e40'
down_revision = '90efb5979fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
