"""empty message

Revision ID: 6b2bb2409861
Revises: c483bac873a5
Create Date: 2022-06-03 04:53:45.803178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b2bb2409861'
down_revision = 'c483bac873a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_to')
    op.drop_column('Artist', 'available_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('available_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
