"""empty message

Revision ID: 7a6ca8f36291
Revises: 546c9e4e7e05
Create Date: 2022-06-01 21:48:16.326915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6ca8f36291'
down_revision = '546c9e4e7e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String(length=400)), nullable=False))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(length=500)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
