"""empty message

Revision ID: c483bac873a5
Revises: 41f07b8a6e2d
Create Date: 2022-06-03 04:43:33.439069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c483bac873a5'
down_revision = '41f07b8a6e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_to', sa.DateTime(), nullable=True))
    op.add_column('Artist', sa.Column('available_from', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_from')
    op.drop_column('Artist', 'available_to')
    # ### end Alembic commands ###
