"""empty message

Revision ID: e2ceac430f97
Revises: 1f484eb18de6
Create Date: 2022-06-03 04:42:48.196459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ceac430f97'
down_revision = '1f484eb18de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_from', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_from')
    # ### end Alembic commands ###
