"""empty message

Revision ID: e324386c5fa7
Revises: abef3886345a
Create Date: 2022-06-03 04:36:02.779682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e324386c5fa7'
down_revision = 'abef3886345a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_from')
    op.drop_column('Artist', 'available_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('available_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
