"""empty message

Revision ID: e68e3fdbd1e9
Revises: e324386c5fa7
Create Date: 2022-06-03 04:36:30.276902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68e3fdbd1e9'
down_revision = 'e324386c5fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_from', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('available_to', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_to')
    op.drop_column('Artist', 'available_from')
    # ### end Alembic commands ###
